name: Nodejs Test Framework
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo 1
    - run: exit 1
    - run: echo 3
    - run: echo 4
    
  
  slack:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
        # run this action to get workflow conclusion
        # You can get conclusion via env (env.WORKFLOW_CONCLUSION)
      - uses: technote-space/workflow-conclusion-action@v1
      - uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          if: always() # Pick up events even if the job fails or is canceled.
          MATRIX_CONTEXT: ${{ toJson(matrix) }} # required
        with:
          #status: custom
          status: ${{ job.status }}
          # status: env.WORKFLOW_CONCLUSION
          author_name: GitHubAction Started on
          #text: 'Unit Test'
          #channel: '#general'
          mention: 'here, U01E2PFRPR9'
          if_mention: failure,cancelled
          fields: repo,commit,eventName,ref,workflow,message,author,job,took
          custom_payload: |
              {
              username: 'GitHub Action CI WorkFlow',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text:
                `${process.env.AS_REPO}\n
                ${process.env.AS_COMMIT}\n 
                ${process.env.AS_EVENT_NAME}\n
                @${process.env.AS_REF}\n
                @${process.env.AS_WORKFLOW}\n
                ${process.env.AS_MESSAGE}\n 
                ${process.env.AS_AUTHOR}\n 
                ${{ job.status }}\n
                ${process.env.AS_TOOK}`,
              }]
              }